# This is the docker-compose script for local development.
# For the latest version of the docker images see:
# https://github.com/Azure/pcs-cli/blob/master/remotemonitoring/single-vm/docker-compose.dotnet.yml
#
# Usage:
# - install Docker Compose, see https://docs.docker.com/compose/install
# - open a console and `cd` into the folder that contains this file
# - note how this file references many environment variables, either set
#   them in the .env file or edit this file adding the values here
# - run `docker-compose up`
# - open the browser at http://127.0.0.1:10443
#
# For more information see
# https://github.com/Azure/azure-iot-pcs-remote-monitoring-dotnet

version: "3"

services:
  reverseproxy:
    image: azureiotpcs/remote-monitoring-nginx:testing
    ports:
      - "8080:10080"
    depends_on:
      - webui
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
    volumes:
      - ./config/nginx.conf:/app/config/nginx.conf:ro

  webui:
    image: azureiotpcs/pcs-remote-monitoring-webui:testing
    depends_on:
      - auth
      - iothubmanager
      - devicesimulation
      - telemetry
      - config
  # NOTE: Volumes disabled for local development, uncomment if enabling auth
  # volumes:
  #   - ./webui-config.js:/app/build/webui-config.js:ro

  auth:
    image: azureiotpcs/pcs-auth-dotnet:testing
    environment:
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET

  iothubmanager:
    image: azureiotpcs/iothub-manager-dotnet:testing
    depends_on:
      - storageadapter
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET

  devicesimulation:
    image: azureiotpcs/device-simulation-dotnet:testing
    depends_on:
      - storageadapter
    environment:
      - PCS_IOTHUB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET
  # How one could mount custom device models
  # NOTE: Volumes disabled for local development
  # volumes:
  #   - ./my-device-models:/app/data:ro

  telemetry:
    image: azureiotpcs/telemetry-dotnet:testing
    depends_on:
      - storageadapter
    environment:
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET

  config:
    image: azureiotpcs/pcs-config-dotnet:testing
    depends_on:
      - storageadapter
      - devicesimulation
      - telemetry
    environment:
      - PCS_STORAGEADAPTER_WEBSERVICE_URL=http://storageadapter:9022/v1
      - PCS_DEVICESIMULATION_WEBSERVICE_URL=http://devicesimulation:9003/v1
      - PCS_TELEMETRY_WEBSERVICE_URL=http://telemetry:9004/v1
      - PCS_AZUREMAPS_KEY
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET

  storageadapter:
    image: azureiotpcs/pcs-storage-adapter-dotnet:testing
    environment:
      - PCS_STORAGEADAPTER_DOCUMENTDB_CONNSTRING
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_APPLICATION_SECRET

  asamanager:
    image: azureiotpcs/asa-manager-dotnet:testing
    depends_on:
      - telemetry
      - iothubmanager
      - config
    environment:
      - PCS_TELEMETRY_DOCUMENTDB_CONNSTRING
      - PCS_TELEMETRY_WEBSERVICE_URL=http://telemetry:9004/v1
      - PCS_CONFIG_WEBSERVICE_URL=http://config:9005/v1
      - PCS_IOTHUBMANAGER_WEBSERVICE_URL=http://iothubmanager:9002/v1
      - PCS_ASA_DATA_AZUREBLOB_ACCOUNT
      - PCS_ASA_DATA_AZUREBLOB_KEY
      - PCS_ASA_DATA_AZUREBLOB_ENDPOINT_SUFFIX
      - PCS_EVENTHUB_CONNSTRING
      - PCS_EVENTHUB_NAME
      - PCS_AUTH_REQUIRED
      - PCS_CORS_WHITELIST
      - PCS_AUTH_ISSUER
      - PCS_AUTH_AUDIENCE
      - PCS_APPLICATION_SECRET
